- hosts: mongodb
  remote_user: ubuntu
  tasks:
    - name: Import the public for APT
      shell: sudo wget -q0 - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
    - name: Create list file for MongoDB
      shell: sudo echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
    - name: Update packages
      shell: sudo apt-get update
    - name: Install Mongo
      shell: sudo apt-get install -y mongodb-org
    - name: Remove Existing Conf File
      shell: sudo rm /etc/mongod.conf
    - name: Copy New Conf File
      shell: sudo ln -s /home/vagrant/env/mongodb/mongd.conf /etc/mongod.conf
    - name: Start Mongo
      shell: sudo systemctl start mongod
    - name: Get Mongo Status
      shell: sudo systemctl status mongod